### ISSUE TITLE
Unpinning ocaml in grewlib

### ISSUE THREAD

**Issue by LoicGrobol** [grew-nlp/grewlib#2]
Hi and thanks for the good work. I have just noticed that the most recent versions of grewlib are pinning ocaml to <4 because of issues with eliom. However not all downstream uses of grewlib need eliom (for instance I work only with grew and grewpy). Would it be possible to only pin ocaml for the downstream packages that need it?

**Comment by bguil** [comment]
Hi @LoicGrobol and thanks for your support!
I've managed to compile `eliom` based code with more recent Ocaml version (5.1.0 or 5.1.1).
I will publish a new grew version without Ocaml 4 constraint ASAP.

**Comment by bguil** [comment]
The latest version released today (1.15) is compatible with the latest Ocaml versions.
See [Grew upgrade](https://grew.fr/usage/install/#grew-upgrade).
